INSERT INTO [Team] VALUES (	1	,'BOS' , '	boston celtics	 ');
INSERT INTO [Team] VALUES (	2	,'BKN' , '	brooklyn nets	 ');
INSERT INTO [Team] VALUES (	3	,'NYK' , '	new york knicks	 ');
INSERT INTO [Team] VALUES (	4	,'PHI' , '	philadelphia 76ers	 ');
INSERT INTO [Team] VALUES (	5	,'TOR' , '	toronto raptors	 ');
INSERT INTO [Team] VALUES (	6	,'GSW' , '	golden state warriors	 ');
INSERT INTO [Team] VALUES (	7	,'LAC' , '	los angeles clippers	 ');
INSERT INTO [Team] VALUES (	8	,'LAL' , '	los angeles lakers	 ');
INSERT INTO [Team] VALUES (	9	,'PHX' , '	phoenix suns	 ');
INSERT INTO [Team] VALUES (	10	,'SAC' , '	sacramento kings	 ');
INSERT INTO [Team] VALUES (	11	,'CHI' , '	chicago bulls	 ');
INSERT INTO [Team] VALUES (	12	,'CLE' , '	cleveland cavaliers	 ');
INSERT INTO [Team] VALUES (	13	,'DET' , '	detroit pistons	 ');
INSERT INTO [Team] VALUES (	14	,'IND' , '	indiana pacers	 ');
INSERT INTO [Team] VALUES (	15	,'MIL' , '	milwaukee bucks	 ');
INSERT INTO [Team] VALUES (	16	,'DAL' , '	dallas mavericks	 ');
INSERT INTO [Team] VALUES (	17	,'HOU' , '	houston rockets	 ');
INSERT INTO [Team] VALUES (	18	,'MEM' , '	memphis grizzlies	 ');
INSERT INTO [Team] VALUES (	19	,'NOP' , '	new orleans pelicans	 ');
INSERT INTO [Team] VALUES (	20	,'SAS' , '	san antonio spurs	 ');
INSERT INTO [Team] VALUES (	21	,'ATL' , '	atlanta hawks	 ');
INSERT INTO [Team] VALUES (	22	,'CHA' , '	charlotte hornets	 ');
INSERT INTO [Team] VALUES (	23	,'MIA' , '	miami heat	 ');
INSERT INTO [Team] VALUES (	24	,'ORL' , '	orlando magic	 ');
INSERT INTO [Team] VALUES (	25	,'WAS' , '	washington wizards	 ');
INSERT INTO [Team] VALUES (	26	,'DEN' , '	denver nuggets	 ');
INSERT INTO [Team] VALUES (	27	,'MIN' , '	minnesota timberwolves	 ');
INSERT INTO [Team] VALUES (	28	,'OKC' , '	oklahoma city thunder	 ');
INSERT INTO [Team] VALUES (	29	,'POR' , '	portland trail blazers	 ');
INSERT INTO [Team] VALUES (	30	,'UTA' , '	utah jazz	 ');