INSERT INTO [Stadium] VALUES (	1	,'TD Garden',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Boston Celtics%'));
INSERT INTO [Stadium] VALUES (	2	,'Spectrum Center',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Charlotte Hornets%'));
INSERT INTO [Stadium] VALUES (	3	,'United Center',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Chicago Bulls%'));
INSERT INTO [Stadium] VALUES (	4	,'Rocket Mortgage FieldHouse',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Cleveland Cavaliers%'));
INSERT INTO [Stadium] VALUES (	5	,'American Airlines Center',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Dallas Mavericks%'));
INSERT INTO [Stadium] VALUES (	6	,'Pepsi Center',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Denver Nuggets%'));
INSERT INTO [Stadium] VALUES (	7	,'Little Caesars Arena',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Detroit Pistons%'));
INSERT INTO [Stadium] VALUES (	8	,'Toyota Center',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Houston Rockets%'));
INSERT INTO [Stadium] VALUES (	9	,'Bankers Life Fieldhouse',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Indiana Pacers%'));
INSERT INTO [Stadium] VALUES (	10	,'Staples Center',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Los Angeles Clippers%'));
INSERT INTO [Stadium] VALUES (	11	,'Chase Center',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Golden State Warriors%'));
INSERT INTO [Stadium] VALUES (	12	,'FedEx Forum',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Memphis Grizzlies%'));
INSERT INTO [Stadium] VALUES (	13	,'American Airlines Arena',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Miami Heat%'));
INSERT INTO [Stadium] VALUES (	14	,'Fiserv Forum',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Milwaukee Bucks%'));
INSERT INTO [Stadium] VALUES (	15	,'Target Center',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Minnesota Timberwolves%'));
INSERT INTO [Stadium] VALUES (	16	,'Barclays Center',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Brooklyn Nets%'));
INSERT INTO [Stadium] VALUES (	17	,'Smoothie King Center',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%New Orleans Pelicans%'));
INSERT INTO [Stadium] VALUES (	18	,'Madison Square Garden',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%New York Knicks%'));
INSERT INTO [Stadium] VALUES (	19	,'Chesapeake Energy Arena',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Oklahoma City Thunder%'));
INSERT INTO [Stadium] VALUES (	20	,'Amway Center',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Orlando Magic%'));
INSERT INTO [Stadium] VALUES (	21	,'Wells Fargo Center',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Philadelphia 76ers%'));
INSERT INTO [Stadium] VALUES (	22	,'Talking Stick Resort Arena',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Phoenix Suns%'));
INSERT INTO [Stadium] VALUES (	23	,'Moda Center',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Portland Trail blazers%'));
INSERT INTO [Stadium] VALUES (	24	,'Golden 1 Center',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Sacramento Kings%'));
INSERT INTO [Stadium] VALUES (	25	,'AT&T Center',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%San Antonio Spurs%'));
INSERT INTO [Stadium] VALUES (	26	,'Scotiabank Arena',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Toronto Raptors%'));
INSERT INTO [Stadium] VALUES (	27	,'Vivint Smart Home Arena',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Utah Jazz%'));
INSERT INTO [Stadium] VALUES (	28	,'Capital One Arena',10000, (SELECT [team-ID] FROM Team WHERE [team-name] LIKE '%Washington Wizards%'));